import jsPDF from 'jspdf';
import { DocumentRecord } from '@/types/document';

export const generatePDFReport = (document: DocumentRecord): void => {
  const pdf = new jsPDF();
  const pageWidth = pdf.internal.pageSize.getWidth();
  const margin = 20;
  const maxWidth = pageWidth - (margin * 2);
  let y = margin;

  // Title
  pdf.setFontSize(20);
  pdf.setTextColor(56, 189, 248);
  pdf.text('AI Document Intelligence Report', margin, y);
  y += 15;

  // Metadata
  pdf.setFontSize(10);
  pdf.setTextColor(100, 100, 100);
  pdf.text(`Generated: ${new Date(document.timestamp).toLocaleString()}`, margin, y);
  y += 7;
  pdf.text(`File: ${document.fileName}`, margin, y);
  y += 7;
  pdf.text(`Confidence: ${document.confidence.toFixed(1)}%`, margin, y);
  y += 15;

  // Extracted Fields
  if (document.fields && document.fields.length > 0) {
    pdf.setFontSize(14);
    pdf.setTextColor(0, 0, 0);
    pdf.text('Extracted Fields', margin, y);
    y += 10;

    pdf.setFontSize(10);
    document.fields.forEach(field => {
      const text = `${field.label}: ${field.value} (${field.confidence}%)`;
      const lines = pdf.splitTextToSize(text, maxWidth);
      pdf.text(lines, margin, y);
      y += 7 * lines.length;
      
      if (y > 270) {
        pdf.addPage();
        y = margin;
      }
    });

    y += 10;
  }

  // Full Text
  pdf.setFontSize(14);
  pdf.setTextColor(0, 0, 0);
  pdf.text('Extracted Text', margin, y);
  y += 10;

  pdf.setFontSize(9);
  const textLines = pdf.splitTextToSize(document.extractedText || 'No text extracted', maxWidth);
  
  textLines.forEach((line: string) => {
    if (y > 280) {
      pdf.addPage();
      y = margin;
    }
    pdf.text(line, margin, y);
    y += 5;
  });

  // Footer
  const totalPages = pdf.internal.pages.length - 1;
  for (let i = 1; i <= totalPages; i++) {
    pdf.setPage(i);
    pdf.setFontSize(8);
    pdf.setTextColor(150, 150, 150);
    pdf.text(
      `Page ${i} of ${totalPages} | Generated by AI Document Extractor`,
      pageWidth / 2,
      pdf.internal.pageSize.getHeight() - 10,
      { align: 'center' }
    );
  }

  // Save
  const fileName = `AI_Report_${new Date(document.timestamp).getTime()}.pdf`;
  pdf.save(fileName);
};
